In [1]:
# reading the document-term matrix
import pandas as pd
import pickle

data = pd.read_pickle('dtm_stop.pkl')
data

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aaah,aah,abc,abcs,ability,abject,...,zee,zen,zeppelin,zero,zillion,zombie,zombies,zoning,zoo,éclair
ali,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,0,1,0,0,...,0,0,0,1,1,1,1,1,0,0
bo,0,1,1,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
dave,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,2,1,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,3,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,2,1,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1,0

In [3]:
pip install gensim

Collecting gensim
  Downloading gensim-4.0.1-cp38-cp38-win_amd64.whl (23.9 MB)
Requirement already satisfied: scipy>=0.18.1 in c:\users\jishn\anaconda3\lib\site-packages (from gensim) (1.6.2)
Requirement already satisfied: numpy>=1.11.3 in c:\users\jishn\anaconda3\lib\site-packages (from gensim) (1.20.1)
Collecting Cython==0.29.21
  Downloading Cython-0.29.21-cp38-cp38-win_amd64.whl (1.7 MB)
Collecting smart-open>=1.8.1
  Downloading smart_open-5.1.0-py3-none-any.whl (57 kB)
Installing collected packages: smart-open, Cython, gensim
  Attempting uninstall: Cython
    Found existing installation: Cython 0.29.23
    Uninstalling Cython-0.29.23:
      Successfully uninstalled Cython-0.29.23
Successfully installed Cython-0.29.21 gensim-4.0.1 smart-open-5.1.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
from gensim import matutils, models
import scipy.sparse

In [6]:
tdm = data.transpose()
tdm.head()

,ali,anthony,bill,bo,dave,hasan,jim,joe,john,louis,mike,ricky
aaaaah,0,0,1,0,0,0,0,0,0,0,0,0
aaaaahhhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaaauuugghhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaahhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaah,0,0,0,0,1,0,0,0,0,0,0,0

In [7]:
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [8]:
cv = pickle.load(open("cv_stop.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

C:\Users\jishn\anaconda3\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.22.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(

In [9]:
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.008*"fucking" + 0.006*"shit" + 0.006*"fuck" + 0.005*"say" + 0.005*"theyre" + 0.005*"going" + 0.005*"want" + 0.005*"oh" + 0.004*"hes" + 0.004*"little"'),
 (1,
  '0.006*"fucking" + 0.005*"good" + 0.005*"cause" + 0.005*"thing" + 0.005*"shit" + 0.005*"didnt" + 0.005*"really" + 0.005*"went" + 0.005*"fuck" + 0.005*"say"')]

In [10]:
# LDA for num_topics = 3
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.010*"shit" + 0.008*"fucking" + 0.006*"fuck" + 0.006*"didnt" + 0.006*"hes" + 0.005*"life" + 0.005*"thing" + 0.005*"guy" + 0.005*"man" + 0.004*"theres"'),
 (1,
  '0.009*"fucking" + 0.006*"say" + 0.005*"little" + 0.005*"fuck" + 0.005*"theyre" + 0.004*"hes" + 0.004*"id" + 0.004*"love" + 0.004*"theres" + 0.004*"went"'),
 (2,
  '0.006*"oh" + 0.006*"going" + 0.006*"say" + 0.005*"fucking" + 0.005*"day" + 0.005*"cause" + 0.005*"really" + 0.005*"shit" + 0.005*"fuck" + 0.005*"theyre"')]

In [11]:
# LDA for num_topics = 4
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.000*"fucking" + 0.000*"want" + 0.000*"shit" + 0.000*"oh" + 0.000*"fuck" + 0.000*"hes" + 0.000*"didnt" + 0.000*"did" + 0.000*"say" + 0.000*"thing"'),
 (1,
  '0.007*"fucking" + 0.006*"shit" + 0.006*"fuck" + 0.006*"say" + 0.005*"cause" + 0.005*"theyre" + 0.005*"thing" + 0.005*"theres" + 0.005*"really" + 0.004*"life"'),
 (2,
  '0.008*"fucking" + 0.006*"going" + 0.006*"oh" + 0.006*"went" + 0.006*"shit" + 0.005*"say" + 0.005*"fuck" + 0.005*"want" + 0.005*"hes" + 0.005*"didnt"'),
 (3,
  '0.000*"fucking" + 0.000*"say" + 0.000*"day" + 0.000*"going" + 0.000*"shit" + 0.000*"cause" + 0.000*"want" + 0.000*"theres" + 0.000*"didnt" + 0.000*"went"')]

In [12]:
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [13]:
data_clean = pd.read_pickle('data_clean.pkl')
data_clean

                                                transcript
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
bill      all right thank you thank you very much thank...
bo       bo what old macdonald had a farm e i e i o and...
dave     this is dave he tells dirty jokes for a living...
hasan      whats up davis whats up im home i had to bri...
jim         ladies and gentlemen please welcome to the ...
joe         ladies and gentlemen welcome joe rogan  wha...
john     armed with boyish charm and a sharp wit the fo...
louis    introfade the music out lets roll hold there l...
mike     wow hey thank you thanks thank you guys hey se...
ricky    hello hello how you doing great thank you wow ...

In [14]:
# Apply the nouns function to the transcripts to filter only on nouns
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i em i francisco city world...
bill     thank thank pleasure georgia area oasis i june...
bo       macdonald farm e i o farm pig e i i snort macd...
dave     jokes living stare work profound train thought...
hasan    whats davis whats home i netflix la york i son...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fuck thanks phone fuckfac...
john     charm wit snl writer john mulaney marriage bee...
louis    music lets lights lights thank i i place place...
mike     wow hey thanks look insane years everyone i id...
ricky    hello thank fuck thank im gon youre weve money...

In [15]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jishn\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [16]:
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i em i francisco city world...
bill     thank thank pleasure georgia area oasis i june...
bo       macdonald farm e i o farm pig e i i snort macd...
dave     jokes living stare work profound train thought...
hasan    whats davis whats home i netflix la york i son...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fuck thanks phone fuckfac...
john     charm wit snl writer john mulaney marriage bee...
louis    music lets lights lights thank i i place place...
mike     wow hey thanks look insane years everyone i id...
ricky    hello thank fuck thank im gon youre weve money...

In [17]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\jishn\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [18]:
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i em i francisco city world...
bill     thank thank pleasure georgia area oasis i june...
bo       macdonald farm e i o farm pig e i i snort macd...
dave     jokes living stare work profound train thought...
hasan    whats davis whats home i netflix la york i son...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fuck thanks phone fuckfac...
john     charm wit snl writer john mulaney marriage bee...
louis    music lets lights lights thank i i place place...
mike     wow hey thanks look insane years everyone i id...
ricky    hello thank fuck thank im gon youre weve money...

In [19]:
# Creating a new document-term matrix using only nouns
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-adding the additional stop words while recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# Recreating a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names())
data_dtmn.index = data_nouns.index
data_dtmn

,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abortion,abortions,abuse,...,yummy,ze,zealand,zee,zeppelin,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,2,0,0,...,0,0,10,0,0,0,0,0,0,0
bill,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,1,1,0,0
bo,1,1,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
ricky,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0

In [20]:
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Creating the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [21]:
# starting with 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.009*"day" + 0.007*"cause" + 0.006*"thing" + 0.006*"dad" + 0.006*"lot" + 0.005*"shes" + 0.005*"life" + 0.005*"women" + 0.005*"shit" + 0.005*"hes"'),
 (1,
  '0.009*"thing" + 0.009*"shit" + 0.009*"man" + 0.008*"life" + 0.008*"day" + 0.008*"hes" + 0.007*"way" + 0.007*"fuck" + 0.006*"guy" + 0.006*"gon"')]

In [22]:
#  topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.010*"stuff" + 0.010*"bo" + 0.009*"repeat" + 0.008*"eye" + 0.007*"contact" + 0.006*"man" + 0.005*"brain" + 0.005*"story" + 0.005*"cos" + 0.004*"comedy"'),
 (1,
  '0.012*"shit" + 0.010*"life" + 0.009*"thing" + 0.008*"hes" + 0.008*"man" + 0.007*"day" + 0.007*"guy" + 0.007*"fuck" + 0.007*"dad" + 0.006*"way"'),
 (2,
  '0.010*"day" + 0.009*"thing" + 0.009*"cause" + 0.007*"way" + 0.007*"man" + 0.006*"hes" + 0.006*"house" + 0.006*"things" + 0.006*"fuck" + 0.006*"theyre"')]

In [23]:
#  4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.011*"day" + 0.009*"joke" + 0.009*"thing" + 0.007*"way" + 0.006*"things" + 0.006*"hes" + 0.006*"years" + 0.006*"man" + 0.005*"life" + 0.005*"stuff"'),
 (1,
  '0.016*"shit" + 0.010*"man" + 0.009*"fuck" + 0.009*"guy" + 0.008*"hes" + 0.007*"gon" + 0.007*"dude" + 0.007*"thing" + 0.006*"way" + 0.006*"lot"'),
 (2,
  '0.012*"life" + 0.011*"shit" + 0.010*"thing" + 0.010*"lot" + 0.009*"cause" + 0.009*"hes" + 0.008*"women" + 0.007*"day" + 0.006*"gon" + 0.005*"theyre"'),
 (3,
  '0.009*"fuck" + 0.008*"day" + 0.008*"cause" + 0.008*"thing" + 0.008*"life" + 0.007*"man" + 0.007*"house" + 0.007*"dad" + 0.007*"shes" + 0.006*"way"')]

In [24]:
#  creating a function to pull out nouns from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [25]:
# Applying the nouns function to the transcripts to filter only on nouns
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                                transcript
ali      ladies gentlemen welcome stage ali wong hi wel...
anthony  thank san francisco thank good people surprise...
bill     right thank thank pleasure greater atlanta geo...
bo       old macdonald farm e i i o farm pig e i i snor...
dave     dirty jokes living stare most hard work profou...
hasan    whats davis whats im home i netflix special la...
jim      ladies gentlemen welcome stage mr jim jefferie...
joe      ladies gentlemen joe fuck san francisco thanks...
john     boyish charm sharp wit former snl writer john ...
louis    music lets lights lights thank much i i i nice...
mike     wow hey thanks hey seattle nice look crazy ins...
ricky    hello great thank fuck thank lovely welcome im...

In [26]:
# Creating a new document-term matrix using only nouns and adjectives
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abject,able,...,ze,zealand,zee,zeppelin,zero,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,0,1,0,0,0,2,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,1,1,1,0,0
bo,0,1,1,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,1,...,0,0,2,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,3,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,1,1,2,...,0,0,0,0,0,0,0,0,1,0

In [27]:
# Creating the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Creating the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [28]:
# start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.005*"mom" + 0.005*"parents" + 0.004*"friend" + 0.003*"hasan" + 0.003*"clinton" + 0.003*"jenny" + 0.003*"wife" + 0.003*"ahah" + 0.003*"door" + 0.003*"york"'),
 (1,
  '0.005*"joke" + 0.003*"ass" + 0.003*"jokes" + 0.003*"gun" + 0.003*"ok" + 0.002*"dead" + 0.002*"dog" + 0.002*"bo" + 0.002*"mom" + 0.002*"dick"')]

In [29]:
# trying 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.005*"mom" + 0.005*"parents" + 0.004*"friend" + 0.003*"door" + 0.003*"clinton" + 0.003*"hasan" + 0.003*"jenny" + 0.003*"wife" + 0.003*"ahah" + 0.003*"york"'),
 (1,
  '0.007*"joke" + 0.005*"bo" + 0.005*"repeat" + 0.004*"anthony" + 0.004*"gun" + 0.004*"eye" + 0.004*"comedy" + 0.004*"contact" + 0.004*"jokes" + 0.003*"sad"'),
 (2,
  '0.004*"joke" + 0.004*"ass" + 0.004*"ok" + 0.003*"guns" + 0.003*"dog" + 0.003*"nuts" + 0.003*"cunt" + 0.003*"tit" + 0.003*"husband" + 0.003*"girlfriend"')]

In [30]:
# trying 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.006*"joke" + 0.006*"clinton" + 0.005*"mom" + 0.004*"cow" + 0.004*"wife" + 0.004*"parents" + 0.004*"nuts" + 0.003*"jenner" + 0.003*"boy" + 0.003*"hampstead"'),
 (1,
  '0.005*"jenny" + 0.004*"tit" + 0.003*"morning" + 0.003*"parents" + 0.003*"gun" + 0.003*"idea" + 0.003*"jesus" + 0.003*"dog" + 0.003*"date" + 0.003*"marriage"'),
 (2,
  '0.005*"hasan" + 0.005*"mom" + 0.004*"ahah" + 0.004*"door" + 0.004*"parents" + 0.003*"nigga" + 0.003*"gay" + 0.003*"brown" + 0.003*"son" + 0.003*"dick"'),
 (3,
  '0.006*"joke" + 0.005*"bo" + 0.004*"um" + 0.004*"guns" + 0.004*"ass" + 0.004*"repeat" + 0.004*"anthony" + 0.004*"eye" + 0.004*"jokes" + 0.004*"ok"')]

In [31]:
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

[(0,
  '0.004*"jenny" + 0.004*"friend" + 0.004*"ass" + 0.004*"guns" + 0.004*"ahah" + 0.003*"son" + 0.003*"door" + 0.003*"class" + 0.003*"girls" + 0.003*"texas"'),
 (1,
  '0.006*"joke" + 0.006*"mom" + 0.005*"hasan" + 0.005*"parents" + 0.004*"anthony" + 0.004*"gun" + 0.003*"mad" + 0.003*"comedy" + 0.003*"brown" + 0.003*"dream"'),
 (2,
  '0.005*"joke" + 0.004*"bo" + 0.004*"clinton" + 0.004*"repeat" + 0.004*"eye" + 0.003*"mom" + 0.003*"dog" + 0.003*"ha" + 0.003*"parents" + 0.003*"food"'),
 (3,
  '0.008*"husband" + 0.007*"ok" + 0.005*"pregnant" + 0.004*"asian" + 0.004*"fingers" + 0.004*"doo" + 0.004*"toilet" + 0.004*"wan" + 0.004*"mom" + 0.003*"body"')]

In [32]:
# Result

# Topic 0: mom, parents
# Topic 1: husband, wife
# Topic 2: guns
# Topic 3: profanity

In [33]:
#  topics each transcript contains
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(3, 'ali'),
 (1, 'anthony'),
 (1, 'bill'),
 (2, 'bo'),
 (0, 'dave'),
 (1, 'hasan'),
 (0, 'jim'),
 (0, 'joe'),
 (2, 'john'),
 (2, 'louis'),
 (0, 'mike'),
 (2, 'ricky')]

In [34]:
# Result

# Topic 0: mom, parents [Anthony, Hasan, Louis, Ricky]
# Topic 1: husband, wife [Ali, John, Mike]
# Topic 2: guns [Bill, Bo, Jim]
# Topic 3: profanity [Dave, Joe]